### ISSUE TITLE
extension is not working

### ISSUE THREAD

**Issue by iamtalhaasghar** [PatilHarshh/Bachhpan#2]
https://github.com/PatilHarshh/Bachhpan/assets/46928648/305bb537-c3e1-4d94-9e03-c8ae3415d545

Clicking on any button does nothing. Am i doing something wrong?

**Comment by PatilHarshh** [comment]
Hello @iamtalhaasghar  , Thanks for interest. Apparently Our extension is not supportive to  firefox anymore , you can try our extension on edge or can use on chrome by downloading source code  . Links are Updated !!
https://microsoftedge.microsoft.com/addons/detail/bachpan/jpakagnjckioanodbjdgojmkcdigochf?hl=en-US
